config/routes.rb
StamfordCabin::Application.routes.draw do
  
  
  root 'static_pages#home'
  match '/info', to: 'static_pages#info', via: 'get'
  match '/pictures', to: 'static_pages#pictures', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def info
  end

  def pictures
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Stamford Holiday Cabin"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class= "footer">
	<small>
		<p>Site built by Rory Munro</p>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Info", info_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class= "navbar navbar-fixed-top navbar">
      <div class= "navbar-inner">
      	<div class="container">
      		<%= link_to "STAMFORD HOLIDAY", root_path, id: "logo" %>
      		  <nav>
      		  	<ul class= "nav pull-right">
                  <li><%= link_to "Home", root_path %></li>
                  <li><%= link_to "Info", info_path %></li>
                  <li><%= link_to "Pictures", pictures_path %></li>
                  <li><%= link_to "Contact", contact_path %></li>
      		  	</ul>
      		  </nav>
      	</div>
      </div> 
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-no-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-no-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52159514-1', 'stamfordcabin.herokuapp.com');
  ga('send', 'pageview');

</script>
  <%= render 'layouts/shim' %>

</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container", id= "main">
<%= yield %>
<%= render 'layouts/footer' %> 
    </div>
    
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class= "center hero-unit", id= "jumb">
  <h1>Contact</h1>
</div>


<div class= "text-center">
  <h2>For bookings or more information, please don't hessitate to contact.</br></br> ROGER MUNRO</h2></br>
  <h3>
  	Telephone: 01780 444058</br>
    Mobile: 07860683771</br>
    Email: rogermunro@aol.com
  </h3>
</div>

app/views/static_pages/home.html.erb
<div class= "center hero-unit", id= "jumb">
	<h1>Welcome to Stamford Holiday Log Cabin</h1>
	
</div>
<div class= "row text-center">
<%= image_tag("cabinfront.JPG", alt: "Log Cabin", id: "homeCabin") %>
</div>

app/views/static_pages/info.html.erb
<% provide(:title, 'Information') %>

<div class= "center hero-unit", id= "jumb">
  <h1>Information</h1>
</div>
<div class= "text-center">
  <h3>For pricing and availability please   <%= link_to "Contact", contact_path, class: "btn  btn-success" %></h3></br>
  <div class= "text-center">
  <p>Perfectly situated just 5 minutes from the historic town of Stamford and the famous Burghley house. Just 10 minutes drive from Rutland water and the East of England Show Ground. Rockingham race track is also 15 minutes away.</p>
</div>
</div>

<div class= "center" id="map-canvas">


<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>

function initialize() {
  var myLatlng = new google.maps.LatLng(52.619885, -0.523137);
  var mapOptions = {
    zoom: 10,
    center: myLatlng
  }
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'Welcome to the log cabin!'
  });
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>

</div>

app/views/static_pages/pictures.html.erb
<% provide(:title, 'Pictures') %>

<div class= "center hero-unit", id= "jumb">
  <h1>Pictures</h1>
</div>


<div class="container">
    <!--  Carousel -->
  <!--  consult Bootstrap docs at
        http://twitter.github.com/bootstrap/javascript.html#carousel -->
  <div id="this-carousel-id" class="carousel slide">
    <div class="carousel-inner">
      <div class="active item">
          <%= image_tag("cabinfront.JPG", alt: "Log Cabin") %>
	    <div class="carousel-caption">
          <p>Enjoy the secluded patio at the front of the cabin (weather permitting)</p>
        </div>
      </div>
      
      <div class="item">
          <%= image_tag("sideCabin.JPG", alt: "Log Cabin") %>
        <div class="carousel-caption">
          <p>The cabin accomodates up to four people.</p>
        </div>
      </div>

      <div class="item">
          <%= image_tag("viewDog.jpg", alt: "Log Cabin") %>
        <div class="carousel-caption">
          <p>Join the dog and enjoy the views over the Welland valley.</p>
        </div>
      </div>

      <div class="item">
          <%= image_tag("sittingroom.JPG", alt: "Sitting Room") %>
        <div class="carousel-caption">
          <p>Relax in the sitting room, where there is a fold out double bed to accomodate a couple of extra people.</p>
        </div>
      </div>

      

      <div class="item">
          <%= image_tag("kitchen.JPG", alt: "Kitchen") %>
        <div class="carousel-caption">
          <p>Fully equipped kitchen.</p>
        </div>
      </div>

      <div class="item">
          <%= image_tag("bathroom.JPG", alt: "Bathroom") %>
        <div class="carousel-caption">
          <p>A large shower in the bathroom.</p>
        </div>
      </div>

      <div class="item">
          <%= image_tag("chicken.jpg", alt: "Chickens") %>
        <div class="carousel-caption">
          <p>Fresh eggs are available.</p>
        </div>
      </div>

      <div class="item">
          <%= image_tag("pig.jpg", alt: "Pigs") %>
        <div class="carousel-caption">
          <p>Go and visit the pigs (unless they've already gone to a better place).</p>
        </div>
      </div>

      <div class="item">
          <%= image_tag("Stamford.jpg", alt: "The george of Stamford") %>
        <div class="carousel-caption">
          <p>Within walking distance of the historic town of Stamford, a site often used as a set for costume dramas.</p>
        </div>
      </div>

    </div><!-- .carousel-inner -->
    <!--  next and previous controls here
          href values must reference the id for this carousel -->
      <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
      <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
  </div>

</div>

<script>
$(function(){
  $('#myCarousel').carousel();
});
</script>